name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: IPUserControls

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}.sln

    # Build the project
    - name: Build project
      run: dotnet build ${{ env.Solution_Name }}.sln --configuration ${{ matrix.configuration }}

    # Pack NuGet package
    - name: Create NuGet package
      #run: dotnet pack ${{ env.Solution_Name }}.sln --configuration ${{ matrix.configuration }} -v d --output ./artifacts
      run: dotnet pack --configuration Release --output .

    # Deploy NuGet package
    - name: Push NuGet package
      #run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      run: dotnet nuget push ./*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
